//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlMappingTaskPane.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlMappingTaskPane.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 (Add New Part...) 的本地化字符串。
        /// </summary>
        internal static string AddNewDataSource {
            get {
                return ResourceManager.GetString("AddNewDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attribute 的本地化字符串。
        /// </summary>
        internal static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Banner {
            get {
                object obj = ResourceManager.GetObject("Banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 CData Section 的本地化字符串。
        /// </summary>
        internal static string CDATA {
            get {
                return ResourceManager.GetString("CDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The friendly name for this custom XML part could not be changed. 的本地化字符串。
        /// </summary>
        internal static string ChangePartNameErrorMessage {
            get {
                return ResourceManager.GetString("ChangePartNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comment 的本地化字符串。
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complete XML Document 的本地化字符串。
        /// </summary>
        internal static string CompleteXMLDocument {
            get {
                return ResourceManager.GetString("CompleteXMLDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Core File Properties 的本地化字符串。
        /// </summary>
        internal static string CoreFilePropertiesName {
            get {
                return ResourceManager.GetString("CoreFilePropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cover Page Properties 的本地化字符串。
        /// </summary>
        internal static string CoverPagePropertiesName {
            get {
                return ResourceManager.GetString("CoverPagePropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click here and enter a date. 的本地化字符串。
        /// </summary>
        internal static string DatePlaceholder {
            get {
                return ResourceManager.GetString("DatePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleting this node will affect any controls in your document that are bound to it. Are you sure? 的本地化字符串。
        /// </summary>
        internal static string DeleteNodeMessage {
            get {
                return ResourceManager.GetString("DeleteNodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleting this data source will affect any content controls in your document that are bound to it.
        ///
        ///Are you sure you want to delete it? 的本地化字符串。
        /// </summary>
        internal static string DeletePartMessage {
            get {
                return ResourceManager.GetString("DeletePartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML Mapping Task Pane 的本地化字符串。
        /// </summary>
        internal static string DialogTitle {
            get {
                return ResourceManager.GetString("DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose... 的本地化字符串。
        /// </summary>
        internal static string DropDownPlaceholder {
            get {
                return ResourceManager.GetString("DropDownPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Element 的本地化字符串。
        /// </summary>
        internal static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A combo box content control cannot be applied to the current selection.
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string ErrorAddComboBox {
            get {
                return ResourceManager.GetString("ErrorAddComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A date picker content control cannot be applied to the current selection.
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string ErrorAddDate {
            get {
                return ResourceManager.GetString("ErrorAddDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A drop-down list content control cannot be applied to the current selection.
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string ErrorAddDropDown {
            get {
                return ResourceManager.GetString("ErrorAddDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This node could not be added:
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string ErrorAddingNode {
            get {
                return ResourceManager.GetString("ErrorAddingNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A picture content control cannot be applied to the current selection.
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string ErrorAddPicture {
            get {
                return ResourceManager.GetString("ErrorAddPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A plain text content control cannot be applied to the current selection.
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string ErrorAddPlainText {
            get {
                return ResourceManager.GetString("ErrorAddPlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected data source could not be deleted:
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string ErrorDeletePart {
            get {
                return ResourceManager.GetString("ErrorDeletePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This node could not be deleted:
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string ErrorDeletingNode {
            get {
                return ResourceManager.GetString("ErrorDeletingNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An element or attribute must have a non-empty name. 的本地化字符串。
        /// </summary>
        internal static string ErrorNoName {
            get {
                return ResourceManager.GetString("ErrorNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This XML file could not be added: 
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string ErrorOnPartAdd {
            get {
                return ResourceManager.GetString("ErrorOnPartAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The text node could not be renamed:
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string ErrorRenamingNode {
            get {
                return ResourceManager.GetString("ErrorRenamingNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your updated settings could not be saved. Any changes will be lost. 的本地化字符串。
        /// </summary>
        internal static string ErrorSaveSettings {
            get {
                return ResourceManager.GetString("ErrorSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extended File Properties 的本地化字符串。
        /// </summary>
        internal static string ExtendedFilePropertiesName {
            get {
                return ResourceManager.GetString("ExtendedFilePropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified file could not be located. 的本地化字符串。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file specified does not contain valid XML:
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string FileNotValidXml {
            get {
                return ResourceManager.GetString("FileNotValidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finish 的本地化字符串。
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Line {
            get {
                object obj = ResourceManager.GetObject("Line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        internal static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading...
        ///{0}% 的本地化字符串。
        /// </summary>
        internal static string LoadingMessageWithPercentage {
            get {
                return ResourceManager.GetString("LoadingMessageWithPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1033 的本地化字符串。
        /// </summary>
        internal static string Locale {
            get {
                return ResourceManager.GetString("Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Namespace 的本地化字符串。
        /// </summary>
        internal static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next &gt; 的本地化字符串。
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (no namespace) 的本地化字符串。
        /// </summary>
        internal static string NoNamespace {
            get {
                return ResourceManager.GetString("NoNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} ({1}) 的本地化字符串。
        /// </summary>
        internal static string NumberedItem {
            get {
                return ResourceManager.GetString("NumberedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click here to enter text. 的本地化字符串。
        /// </summary>
        internal static string PlainTextPlaceholder {
            get {
                return ResourceManager.GetString("PlainTextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prefix Mappings 的本地化字符串。
        /// </summary>
        internal static string Prefixes {
            get {
                return ResourceManager.GetString("Prefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing Instruction 的本地化字符串。
        /// </summary>
        internal static string ProcessingInstruction {
            get {
                return ResourceManager.GetString("ProcessingInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RibbonIcon {
            get {
                object obj = ResourceManager.GetObject("RibbonIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 The string specified does not contain valid XML:
        ///
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string StringNotValidXml {
            get {
                return ResourceManager.GetString("StringNotValidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML Mapping 的本地化字符串。
        /// </summary>
        internal static string TaskPaneName {
            get {
                return ResourceManager.GetString("TaskPaneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Node Type 的本地化字符串。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML 的本地化字符串。
        /// </summary>
        internal static string XML {
            get {
                return ResourceManager.GetString("XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XPath 的本地化字符串。
        /// </summary>
        internal static string XPath {
            get {
                return ResourceManager.GetString("XPath", resourceCulture);
            }
        }
    }
}
